import type { Metadata } from "next";
import { Inter, Istok_Web, Manrope, Roboto } from "next/font/google";
import "./globals.css";
import { TelegramProvider } from "@/lib/TelegramProvider";

const inter = Inter({ subsets: ["latin"] });

const manrope = Manrope({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

const istok = Istok_Web({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${istok.className} ${inter.className} ${roboto.className} `}
      >
        <TelegramProvider>{children}</TelegramProvider>
      </body>
    </html>
  );
}
